FROM centos:7
MAINTAINER: "Eric Rumble"

# Ensure the container is up to date
RUN yum makecache fast \
 && yum update -y \
 && yum install -y \
        rpm-build \
        tar \
        make \
        readline-devel \
        ncurses-devel \
        gdbm-devel \
        glibc-devel \
        gcc \
        openssl-devel \
        libyaml-devel \
        libffi-devel \
        zlib-devel \
 && yum clean all

# create builder user and group per rpmbuild's recommendation
RUN useradd -u 1000 builder
RUN mkdir -p /home/builder/rmpbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS} \
 && chown -R builder:builder /home/builder

# drop the rpm-build script and spec file
ADD ../scripts/build-rpm.sh /home/builder/rpmbuild/
ADD ../specs/ruby.spec /home/builder/rpmbuild/SPECS/
RUN chmod 755 /home/builder/rpmbuild/build-rpm.sh

WORKDIR /home/builder/rpmbuild
